#!/bin/bash
echo hello


$HOME in heredoc shouldnt expand 
cat<< here | ls ls working
sgec cd
segv ctrl d

minishell> ||
minishell: syntax error near unexpected token `|'
minishell(31148,0x111849dc0) malloc: *** error for object 0x7fcf59e07000: pointer being freed was not allocated
minishell(31148,0x111849dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    31148 abort      ./minishell